FROM node:16.13.0-alpine
#16.13.0-alpine

WORKDIR /

ARG JIRA_USER
ARG JIRA_PASSWORD
ARG JIRA_PROJECT
ARG JIRA_URI
ARG ISSUE_TYPE
ARG GH_TOKEN
ARG GH_TAG
ARG SLACK_WEBHOOK
ARG GH_PR_NUMBER

# ARG RUNS_ON_GITHUB

ENV JIRA_USER=$JIRA_USER \
    JIRA_PASSWORD=$JIRA_PASSWORD \
    JIRA_PROJECT=$JIRA_PROJECT \
    JIRA_URI=$JIRA_URI \
    ISSUE_TYPE=$ISSUE_TYPE \
    GH_TOKEN=$GH_TOKEN \
    GH_TAG=$GH_TAG \
    GH_PR_NUMBER=$GH_PR_NUMBER \
    SLACK_WEBHOOK=$SLACK_WEBHOOK

COPY index.js package.json package-lock.json ./
COPY config/ ./config
COPY helpers/ ./helpers

RUN npm install

ENTRYPOINT ["node", "/index.js"]
