FROM node:16.13.0-alpine

WORKDIR /

ARG JIRA_USER
ARG JIRA_PASSWORD
ARG JIRA_PROJECT
ARG JIRA_URI
ARG ISSUE_TYPE
ARG GH_TOKEN
ARG GH_TAG
ARG SLACK_WEBHOOK
ARG GH_PR_NUMBER
ARG DEPLOYS_BOT_HEADER
ARG DEPLOYS_BOT_HEADER_VALUE

# ARG RUNS_ON_GITHUB

ENV JIRA_USER=$JIRA_USER \
    JIRA_PASSWORD=$JIRA_PASSWORD \
    JIRA_PROJECT=$JIRA_PROJECT \
    JIRA_URI=$JIRA_URI \
    ISSUE_TYPE=$ISSUE_TYPE \
    GH_TOKEN=$GH_TOKEN \
    GH_TAG=$GH_TAG \
    GH_PR_NUMBER=$GH_PR_NUMBER \
    SLACK_WEBHOOK=$SLACK_WEBHOOK \
    DEPLOYS_BOT_HEADER=$DEPLOYS_BOT_HEADER \
    DEPLOYS_BOT_HEADER_VALUE=$DEPLOYS_BOT_HEADER_VALUE

COPY index.js package.json package-lock.json ./
COPY config/ ./config
COPY helpers/ ./helpers

RUN npm install

ENTRYPOINT ["node", "/index.js"]
